### ISSUE TITLE
Copper tools cannot be repaired with the grindstone

### ISSUE THREAD

**Issue by tungstonminer** [redy1aye/CopperEquipmentForge#4]
Placing a copper tool in the grindstone UI works, but the original material used to make the tool cannot be placed in the UI with it.  Thus, it's impossible to actually repair the tool.

**Comment by redy1aye** [comment]
The grindstone is not designed to repair tools with their material. To do this, as in vanilla minecraft, you need to use an anvil. A grindstone is needed to repair an item with the same item and remove enchantments.

Current versions use vanilla copper ingots to repair, but future versions will have compressed copper ingots.

![image](https://user-images.githubusercontent.com/86603844/150671452-c9873607-2eb7-4655-9b36-4e9aa1b5239a.png)
![image](https://user-images.githubusercontent.com/86603844/150671513-fbf6b8ba-5cdf-4aa1-9bc1-d9e59e58182d.png)

**Comment by tungstonminer** [comment]
Got it, thanks!  I'm new to 1.18, and I mistook the working of the grindstone.  :-)
